# Generated by Django 3.0.3 on 2020-02-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodomain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mytodoPost',
        ),
    ]
